### ISSUE TITLE
Article Content Previewer

### ISSUE THREAD

**Issue by ghatch** [geekwiki/blog#22]
Creating a page that contributors/authors can use to write/preview articles would be very handy. Something like the [markdown-it](https://markdown-it.github.io/)<sup>([Src](https://github.com/markdown-it/markdown-it))</sup> demo previewer would be handy, as it would show them the article using the GW css (and JS.. ). [markdown-it](https://github.com/markdown-it/markdown-it)

**Comment by jhyland87** [comment]
Closing this, since articles wont be submitted via the UI, they are managed 100% via Git
